### ISSUE TITLE
Page disabled when in wrong network.

### ISSUE THREAD

**Issue by cblanquera** [gentlyawesome/liliannaroll-nft#1]
![image](https://user-images.githubusercontent.com/120378/150661295-3ff04544-cd29-4353-b825-c7f70f9bf563.png)

 1. I enter the website, 
 2. it pings me to connect my meta mask. 
 3. I connect
 4. it throws an error that im on the wrong network
 5. I change it to the right network
 6. I cannot do anything

I need to refresh the page to make it working again.

**Comment by gentlyawesome** [comment]
I tried this:
https://www.awesomescreenshot.com/video/6983015?key=459b1e2a6bbfb42b1d6bafb95c5b5c4d

**Comment by cblanquera** [comment]
https://www.awesomescreenshot.com/video/6983451?key=bb30a98ae790cc2d734b892e83f8be8e

It's still kind of wonky. for example: I cant click gentleman bax. Like in these situations, I notify the user whats happening so I know to wait or if it's okay to proceed.

**Comment by cblanquera** [comment]
This works now thanks.
